# docker-compose.yml
version: "3.9"
services:
  banner-server:
    build: .
    image: app
    restart: always
    depends_on:
      - postgres
      - migration
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/bannerdb
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  migration:
    build: .
    image: app
    command: npx prisma migrate dev
    volumes:
      - .:/app/
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:13-master
    hostname: postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bannerdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/bannerdb
    ports:
      - 5555:5555

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

volumes:
  postgres-data:
  pgadmin-data:
